name: Update GitHub pages
run-name: Render quarto and publish on GitHub pages

# Source: https://quarto.org/docs/publishing/github-pages.html

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and publish to GitHub pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: index.qmd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}